Add mesh class and test
cb-cities/pipe-network pull request #15
Opened 2018-07-25 07:41 UTC by zs0930

2018-08-02 09:55 UTC, kks32 requested changes
Please move the `Graph` part to a different class entirely and call it `Graph`

2018-08-02 09:55 UTC, kks32 commented on include/mesh.h
> +  ~Mesh() {
Use default destructor

2018-08-02 09:55 UTC, kks32 commented on include/mesh.h
> +  void create_node(unsigned id, Eigen::Vector3d coords) {
Pass coordinates as a const reference

2018-08-02 09:55 UTC, kks32 commented on include/mesh.h
> +  void duplicate_node() {
Rewrite this using `range-based-for` loops and/or STL algorithms / Lambda functions

2018-08-02 09:55 UTC, kks32 commented on include/mesh.h
> +  void duplicate_node() {
Return a bool

2018-08-02 09:55 UTC, kks32 commented on include/mesh.h
> +  std::shared_ptr<pipenetwork::Node> node(unsigned id) {
Never, ever, return an owned pointer. Remove this completely.

2018-08-02 09:55 UTC, kks32 commented on include/mesh.h
> +  void duplicate_node() {
Duplicate node should be checked before a node is added to the mesh, not after.

2018-08-02 09:55 UTC, kks32 commented on include/mesh.h
> +  void redundant_node() {
What's the difference between a redundant node and a duplicate_node?

2018-08-02 09:55 UTC, kks32 commented on include/mesh.h
> +#ifndef PIPE_NETWORK_MESH_H_
Header should only declare the functions, not define them. Use a source file to define your functions.

2018-08-02 09:55 UTC, kks32 commented on include/mesh.h
> +  void duplicate_pipe() {
Same as nodes, should be done at creation, not after.

2018-08-02 09:55 UTC, kks32 commented on include/mesh.h
> +  //! Return a pipe pointer for a given pipe index
Remove this section

2018-08-02 09:55 UTC, kks32 commented on include/mesh.h
> +  //! Return degree centrality (number of pipe connected to the node) of a given
Move it to a `Graph` class

2018-08-02 09:55 UTC, kks32 commented on include/mesh.h
> +  //! corelate pipe id with nodes at its ends
You don't need this, redundant. `pipes_` should have this information.

2018-08-02 09:55 UTC, kks32 commented on include/mesh.h
> +  bool is_betweenness_centrality_{false};
Why is this needed?

2018-08-02 09:55 UTC, kks32 commented on tests/mesh_test.cc
> +  for (unsigned i = 0; i < nodeids.size(); ++i)
In the mesh, create nodes from a list of coordinates.

2018-08-02 09:55 UTC, kks32 commented on tests/mesh_test.cc
> +  mesh->duplicate_node();
This should be checked to return a bool

2018-08-04 08:39 UTC, kks32 requested changes

2018-08-04 08:39 UTC, kks32 commented on include/mesh.cc
> +void Mesh::create_node(std::vector<unsigned> id,
`create_nodes`

2018-08-04 08:39 UTC, kks32 commented on include/mesh.cc
> +void Mesh::create_node(std::vector<unsigned> id,
Give a starting unique id, and increment automatically, no need for a vector of ints

2018-08-04 08:39 UTC, kks32 commented on include/mesh.cc
> +  // Check whether there are duplicate indices or coordinates
Remove this entirely

2018-08-04 08:39 UTC, kks32 commented on include/mesh.cc
> +  if (coords.size() > 1) {
no need to check for coords.size

2018-08-04 08:39 UTC, kks32 commented on include/mesh.cc
> +    for (auto iter1 = coords.begin(); iter1 != std::prev(coords.end());
This is not required

2018-08-04 08:39 UTC, kks32 commented on include/mesh.cc
> +void Mesh::create_pipe(std::vector<unsigned> pipeid,
just pass an initial id, and then increment it.

2018-08-04 08:39 UTC, kks32 commented on include/mesh.cc
> +    pipes_.insert(std::pair<unsigned, std::unique_ptr<pipenetwork::Pipe>>(
use `emplace_back`

2018-08-05 08:25 UTC, kks32 requested changes

2018-08-05 08:25 UTC, kks32 commented on include/mesh.cc
> +void Mesh::create_nodes(std::vector<Eigen::Vector3d> coords) {
Pass coords as a const reference.

2018-08-05 08:25 UTC, kks32 commented on include/mesh.cc
> +    index++;
++index;

2018-08-05 08:25 UTC, kks32 commented on include/mesh.cc
> +  for (auto& coord : coords) {
const auto&

2018-08-05 08:25 UTC, kks32 commented on include/mesh.cc
> +void Mesh::create_pipes(std::vector<std::pair<unsigned, unsigned>> nodeids) {
pass as const reference

2018-08-05 08:25 UTC, kks32 commented on include/mesh.cc
> +void Mesh::create_pipes(std::vector<std::pair<unsigned, unsigned>> nodeids) {
Use node ids as `unsigned long long`, it would be easier to create an alias for `unsigned long long`

2018-08-05 08:25 UTC, kks32 commented on include/mesh.cc
> +//! \retval the status to indicate whether isolated node exists
Remove this comment

2018-08-05 08:25 UTC, kks32 commented on include/mesh.cc
> +bool Mesh::isolated_node() {
Return a list of isolated nodes and remove them from mesh

2018-08-05 08:25 UTC, kks32 commented on include/mesh.h
> +  std::vector<Eigen::Vector3d> nodal_coordinates();
Why do we need this?

2018-08-06 12:23 UTC, kks32 requested changes

2018-08-06 12:23 UTC, kks32 commented on include/mesh.cc
> +  unsigned long long index = 1;
Why is the index starting at 1?

2018-08-06 16:45 UTC, kks32 requested changes

2018-08-06 16:45 UTC, kks32 commented on include/mesh.cc
> +  unsigned long long index = 1;
Could you use an alias for `unsigned long long` as `Index` or somethign

2018-08-06 22:11 UTC, kks32 requested changes

2018-08-06 22:11 UTC, kks32 commented on include/mesh.cc
>    for (const auto& nodeid : nodeids) {
What happens when a certain node id can't be found? Can you handle that exception please?

2018-08-06 22:11 UTC, kks32 commented on tests/mesh_test.cc
> +  nodepair.emplace_back(std::make_pair(2, 4));
Add tests cases to check failure cases as well

2018-08-06 22:11 UTC, kks32 commented on tests/mesh_test.cc
> +  std::vector<std::pair<Index, Index>> nodepair;
rename to `node_pairs`

2018-08-07 13:58 UTC, kks32 requested changes

2018-08-07 13:58 UTC, kks32 commented on include/mesh.cc
> +  // Check whether input nodal indices exist
Remove lines #13 - #28

2018-08-07 13:58 UTC, kks32 commented on include/mesh.cc
> +  // Create pipe pointers
Use a try block and catch excpetion. Exception will be thrown because you are using `at`

2018-08-07 13:58 UTC, kks32 commented on include/mesh.cc
> +  // Create pipe pointers
Return true if no exception is thrown

2018-08-07 13:58 UTC, kks32 commented on include/mesh.cc
> +  for (const auto& inode : isolated_nodes) nodes_.erase(inode->id());
Rename `inode` to `isolated_node`

2018-08-07 13:58 UTC, kks32 commented on include/mesh.cc
> +std::vector<std::shared_ptr<pipenetwork::Node>> Mesh::isolated_nodes() {
Rename to `remove_unconnected_nodes`

2018-08-07 13:58 UTC, kks32 commented on include/mesh.cc
> +  std::vector<std::shared_ptr<pipenetwork::Node>> isolated_nodes;
no need to return a vector of ids

2018-08-07 13:58 UTC, kks32 commented on include/mesh.h
> +#include <iterator>
what's this for?

2018-08-07 23:06 UTC, kks32 requested changes

2018-08-07 23:06 UTC, kks32 commented on include/mesh.cc
> +  Index index = 0;
move try to here!

```
try {
   Index index = 0;
... 
}
```

2018-08-07 23:06 UTC, kks32 commented on include/mesh.cc
> +  bool no_exception = true;
use `status` instead of `no_exception`

2018-08-07 23:06 UTC, kks32 commented on include/mesh.cc
> +  std::vector<std::shared_ptr<pipenetwork::Node>> isolated_nodes;
Remove this!

2018-08-07 23:06 UTC, kks32 commented on tests/mesh_test.cc
> +  bool all_pipe_created = mesh->create_pipes(node_pairs);
Test case where you throw an exception, and test where you don't.

2018-08-07 23:06 UTC, kks32 commented on tests/mesh_test.cc
> +  const Eigen::Vector3d coords1(0.0, 0.0, 0.0);
Can I see a reference for initialisation of an Eigen vector using `()`?

2018-08-07 23:14 UTC, kks32 requested changes

2018-08-07 23:14 UTC, kks32 commented on include/mesh.cc
> +    if (connect == false) isolated_nodes.emplace_back(node.second);
Do `if (!is_connected)`

2018-08-07 23:14 UTC, kks32 commented on include/mesh.cc
> +    bool connect = false;
rename to `is_connected`

2018-08-07 23:21 UTC, zs0930 commented on tests/mesh_test.cc
> +  const Eigen::Vector3d coords1(0.0, 0.0, 0.0);
https://eigen.tuxfamily.org/dox/group__TutorialMatrixArithmetic.html

2018-08-08 13:04 UTC, kks32 approved these changes

2018-08-08 13:04 UTC, merged

2018-08-08 13:06 UTC, kks32 commented
Fixes #3